version: '3'

services:
  postgresql:
    restart: always
    container_name: weather_db
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=weatherdb
    volumes:
      - drf_db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


volumes:
  drf_db_data: