# Generated by Django 4.2.1 on 2023-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userapp",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
