# Generated by Django 4.2.1 on 2023-05-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("City", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("created", models.DateTimeField(auto_now=True, db_index=True, verbose_name="Created")),
                (
                    "send_time_email",
                    models.SmallIntegerField(
                        choices=[("1", "1"), ("3", "3"), ("6", "6"), ("12", "12")],
                        default=1,
                        verbose_name="Send time email",
                    ),
                ),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriprions",
                        to="City.city",
                        verbose_name="City id",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "ordering": ["-created"],
            },
        ),
    ]
