# Generated by Django 4.2.1 on 2023-05-12 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FollowList", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followlist",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriprions_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Use",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="followlist",
            unique_together={("user_id", "city_id")},
        ),
    ]
