# Generated by Django 4.2.1 on 2023-05-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FollowList", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="followlist",
            name="send_time_email",
            field=models.SmallIntegerField(
                choices=[(1, 1), (3, 3), (6, 6), (12, 12)], default=1, verbose_name="Send time email"
            ),
        ),
        migrations.AlterField(
            model_name="followlist",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriprions_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
